# docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/flaskProject123
    ports:
      - "8080:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: flask-backend-db
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=medtest
      - POSTGRES_DB=medtest
      - POSTGRES_HOST=localhost
    ports:
      - 5432
