"""initdb2

Revision ID: 783a0aea95f7
Revises: 0c45be0ea288
Create Date: 2022-04-29 23:53:05.134469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783a0aea95f7'
down_revision = '0c45be0ea288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
